language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install rabbitmq-server -qq
  - sudo service rabbitmq-server start

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --colors --verbose --coverage-clover build/logs/clover.xml

after_script: if [ $(phpenv version-name) = "5.6" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi
